---
- name: Выключение основного домен контроллера на 300 секунд
  block:
    - name: Определить основной интерфейс
      set_fact:
        primary_iface_name: >-
          {{
              ansible_interfaces
              | difference(['lo'])
              | select('match', '^(eth|en)[a-z0-9]*')
              | first
          }}
    
    - name: Выключение интерфейса
      shell: >
        ifdown {{ primary_iface_name }} \
        && sleep 300 \
        && ifup {{ primary_iface_name }}
      async: 10
      poll: 0
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]

- name: Подготовка и обновление пакетов
  include_tasks: prepare.yml
  when:
    - inventory_hostname in groups.get('reachable_clients', [])

- name: Ввод в домен
  include_tasks: ad_prerare.yml
  when:
    - inventory_hostname in groups.get('reachable_clients', [])

- name: Проверка сервисов
  include_tasks: services_check.yml
  when:
    - inventory_hostname in groups.get('reachable_clients', [])
...
